#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml

home:
    path:       /
    controller: App\Controller\frontController::home

single-tricks:
    path:       /single
    controller: App\Controller\frontController::tricks