---
- hosts: all

  vars:
    symfony_root_dir: "/var/www/html/Symfony-Snowtricks"
    symfony_web_dir: "{{ symfony_root_dir }}/public"
    symfony_var_dir: "{{ symfony_root_dir }}/var"
    server_name: vps

  tasks:
    - ping: ~

    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes

    - name: Upgrade installed packages
      become: true
      apt:
        upgrade: safe

    - name: Install Git VCS
      become: true
      apt:
        name: git
        state: latest

    - name: Add PHP 7 PPA repository
      become: true
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install nginx web server
      become: true
      apt:
        name: nginx
        state: latest
      notify: Restart Nginx

    # MySQL requirements
    - name: Set MySQL root password before installing
      become: true
      debconf: name='mysql-server' question='mysql/root_password' value='root' vtype='password'
      changed_when: false

    # MySQL requirements
    - name: Confirm MySQL root password before installing
      become: true
      debconf: name='mysql-server' question='mysql/root_password_again' value='root' vtype='password'
      changed_when: false

    - name: Install MySQL DB server
      become: true
      apt:
        name: mysql-server
        state: latest


    - name: Install PHP packages
      become: true
      apt:
        name:
          - php7.3-cli
          - php7.3-curl
          - php7.3-fpm
          - php7.3-intl
          - php7.3-mysql
          - php7.3-xml
        state: latest
      notify: Restart PHP-FPM

    - name: Set date.timezone for CLI
      become: true
      lineinfile:
        dest: /etc/php/7.1/cli/php.ini
        regexp: "date.timezone ="
        line: "date.timezone = UTC"

    - name: Set date.timezone for FPM
      become: true
      lineinfile:
        dest: /etc/php/7.1/fpm/php.ini
        regexp: "date.timezone ="
        line: "date.timezone = UTC"
      notify: Restart PHP-FPM

    - name: Create project directory and set its permissions
      become: true
      file:
        path: "{{ symfony_root_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes


    #- name: Remove Symfony directory
      #command: 'rm -r {{ symfony_root_dir }}'

    - name: Checkout Git repository
      git:
        repo: https://github.com/DurandSacha/Symfony-Snowtricks
        dest: "{{ symfony_root_dir }}"
        force: yes
        clone: yes   # no

    - name: Install low-level utilities
      become: true
      apt:
        name:
          - zip
          - unzip

    - name: Fix var directory permissions
      file:
        path: "{{ symfony_var_dir }}"
        state: directory
        mode: 0777
        recurse: yes

    - name: Download Composer
      become: true
      apt:
        name: composer
        state: latest

    - name: Set permissions on Composer
      become: true
      file:
        path: /usr/bin/composer
        mode: "a+x"

    - name: Composer install command
      shell: composer install
      args:
        chdir: "{{ symfony_root_dir }}"


    - name: Install Composer's dependencies
      composer:
        working_dir: "{{ symfony_root_dir }}"
        no_dev: no

    - name: Add Symfony config template to the Apache available sites
      become: true
      template:
        src: templates/symfony.conf
        dest: "/etc/nginx/sites-available/{{ server_name }}.conf"
      notify: Restart Nginx

    - name: Enable Symfony config template from Nginx available sites
      become: true
      file:
        src: "/etc/nginx/sites-available/{{ server_name }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
        state: link

    - name: Add enabled nginx site to /etc/hosts
      become: true
      lineinfile:
        dest: /etc/hosts
        regexp: "{{ server_name }}"
        line: "127.0.0.1 {{ server_name }}"

  handlers:

    - name: Restart Nginx
      become: true
      service:
        name: nginx
        state: restarted

    - name: Restart PHP-FPM
      become: true
      service:
        name: php7.1-fpm
        state: restarted